//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkDelivery
    {
        public int ID { get; set; }
        public int DeliveryID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> BinCenterID { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public Nullable<System.DateTime> AcceptDT { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public Nullable<int> StkBalID { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> UOMID { get; set; }
    }
}
