//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkItemStatusConversion
    {
        public int ID { get; set; }
        public int ItemStatusConversionID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> StkBalanceID { get; set; }
        public int UOMID { get; set; }
        public Nullable<int> BinID { get; set; }
        public int Quantity { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public Nullable<int> NewStkBalanceID { get; set; }
    }
}
