//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkModelUOM
    {
        public int ID { get; set; }
        public int ModelID { get; set; }
        public int UOMID { get; set; }
        public int UOMLevel { get; set; }
        public Nullable<decimal> ConversionFactor { get; set; }
        public Nullable<decimal> ConversionFactorToSmallest { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> IsSmallest { get; set; }
        public Nullable<bool> SalesUOM { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> LastAccessID { get; set; }
    }
}
