//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkPurchase
    {
        public int ID { get; set; }
        public int PurchaseID { get; set; }
        public int ModelID { get; set; }
        public int ColourID { get; set; }
        public int TypeID { get; set; }
        public int Qty { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Remark { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
