//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkRepair
    {
        public int ID { get; set; }
        public int RepairID { get; set; }
        public int OldItemID { get; set; }
        public Nullable<int> NewItemID { get; set; }
        public bool Active { get; set; }
        public string CDate { get; set; }
        public string CTime { get; set; }
        public string FDate { get; set; }
        public string FTime { get; set; }
        public string RDate { get; set; }
        public string RTime { get; set; }
        public int AccessID { get; set; }
        public string GSXExpiry { get; set; }
    }
}
