//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkReplaceEB
    {
        public int ID { get; set; }
        public int ReplaceEBID { get; set; }
        public string ContactNo { get; set; }
        public string CustomerName { get; set; }
        public int OldItemID { get; set; }
        public Nullable<int> NewItemID { get; set; }
        public string ProblemRemarks { get; set; }
        public string DiagnoseNote { get; set; }
        public string CaseOutcome { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int LastAccessID { get; set; }
        public Nullable<System.DateTime> ReturnDT { get; set; }
        public bool IsReversal { get; set; }
        public Nullable<int> OldStatusID { get; set; }
        public Nullable<int> OldAccessID { get; set; }
        public bool Active { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public bool IsAddressChanged { get; set; }
        public string ICNo { get; set; }
    }
}
