//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkTransferBal
    {
        public int ID { get; set; }
        public int TransferID { get; set; }
        public Nullable<int> StkBalID { get; set; }
        public int Qty { get; set; }
        public Nullable<int> UOMID { get; set; }
        public Nullable<System.DateTime> TransferDT { get; set; }
        public int AcceptQty { get; set; }
        public Nullable<System.DateTime> AcceptDT { get; set; }
        public Nullable<System.DateTime> RejectDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SmallestQty { get; set; }
        public Nullable<int> AcceptSmallestQty { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
