//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class lnkTransferDiagnosi
    {
        public int ID { get; set; }
        public int DiagnosisItemID { get; set; }
        public int DiagnosisQty { get; set; }
        public int TransferDiagnosisID { get; set; }
        public Nullable<int> ReturnTransferID { get; set; }
        public string Outcome { get; set; }
        public string Remark { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> DiagnosisDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public Nullable<int> TransferID { get; set; }
    }
}
