//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class logTransferItem
    {
        public int ID { get; set; }
        public int TransferID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<int> StkBalID { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Action { get; set; }
        public System.DateTime CreateDT { get; set; }
        public int AccessID { get; set; }
    }
}
