//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class refCenter
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string LocatorCode { get; set; }
        public string LocatorName { get; set; }
        public int CenterTypeID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public int RegionID { get; set; }
        public string PICName { get; set; }
        public string PICEmail { get; set; }
        public string PICMobileNo { get; set; }
        public string PICContactNo { get; set; }
        public string PICFaxNo { get; set; }
        public string Address { get; set; }
        public int StateID { get; set; }
        public int CityID { get; set; }
        public string PostCode { get; set; }
        public int CountryID { get; set; }
        public string Remark { get; set; }
        public string CenterName { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string AddressLine3 { get; set; }
        public int TenantID { get; set; }
    }
}
