//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class refPrice
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public int ModelID { get; set; }
        public Nullable<int> ColourID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public System.DateTime StartDT { get; set; }
        public System.DateTime EndDT { get; set; }
        public Nullable<decimal> SellingPrice { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> LastAccessID { get; set; }
        public int TenantID { get; set; }
    }
}
