//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDiagnosisItem
    {
        public int ID { get; set; }
        public int ReturnTransferID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public int StkBalID { get; set; }
        public int Qty { get; set; }
        public int CenterID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<System.DateTime> DiagnosisDT { get; set; }
        public int BalanceQty { get; set; }
        public int AccessID { get; set; }
    }
}
