//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExtApp
    {
        public int ID { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> SuspendDT { get; set; }
        public Nullable<int> CreateAccessID { get; set; }
        public Nullable<int> UpdateAccessID { get; set; }
        public Nullable<int> SuspendAccessID { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
