//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblItem
    {
        public int ID { get; set; }
        public int StkBalID { get; set; }
        public Nullable<int> BizUnitID { get; set; }
        public int CenterID { get; set; }
        public Nullable<int> DistributorID { get; set; }
        public int ModelID { get; set; }
        public int ColourID { get; set; }
        public int TypeID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ExtOrderID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public Nullable<int> StatusConversionID { get; set; }
        public Nullable<int> AllocationID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public Nullable<int> SalesID { get; set; }
        public Nullable<int> RepairID { get; set; }
        public string SerialNumber { get; set; }
        public string IMEINumber { get; set; }
        public string PINNumber { get; set; }
        public string Prefix { get; set; }
        public string SerialNoFrom { get; set; }
        public string SerialNoTo { get; set; }
        public string BoxNumber { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> IntStatusID { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<int> StockReturnID { get; set; }
        public Nullable<bool> IsConsignment { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
