//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStkJournal
    {
        public int ID { get; set; }
        public string TransType { get; set; }
        public int TransID { get; set; }
        public int StkBalID { get; set; }
        public string Operation { get; set; }
        public int Qty { get; set; }
        public int BeforeQty { get; set; }
        public int AfterQty { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
