//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStkMovement
    {
        public int ID { get; set; }
        public System.DateTime TransDate { get; set; }
        public int BizUnitID { get; set; }
        public int CenterID { get; set; }
        public int ModelID { get; set; }
        public int ColourID { get; set; }
        public int TypeID { get; set; }
        public int OpeningBal { get; set; }
        public int GR { get; set; }
        public int GI { get; set; }
        public int TransferIn { get; set; }
        public int TransferOut { get; set; }
        public int ClosingBal { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
