//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpItemCodeModel
    {
        public int ID { get; set; }
        public string ItemCode { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string ModelName { get; set; }
        public bool NeedStock { get; set; }
        public Nullable<int> BrandID { get; set; }
        public Nullable<bool> IsSerialized { get; set; }
        public Nullable<bool> CanScan { get; set; }
        public Nullable<bool> HasIMEI { get; set; }
        public Nullable<bool> HasSerial { get; set; }
        public Nullable<int> ModelID { get; set; }
        public string ColourName { get; set; }
        public Nullable<int> ColourID { get; set; }
        public Nullable<int> SerialFrom { get; set; }
        public Nullable<int> SerialTo { get; set; }
        public bool IsItemCodeExist { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
