//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpItemUpload
    {
        public int ID { get; set; }
        public Nullable<int> ModelID { get; set; }
        public Nullable<int> ColourID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> UOMID { get; set; }
        public int BizUnitID { get; set; }
        public Nullable<int> CenterID { get; set; }
        public Nullable<int> BinCenterID { get; set; }
        public Nullable<int> DeliveryID { get; set; }
        public string SerialNumber { get; set; }
        public string IMEINumber { get; set; }
        public string PINNumber { get; set; }
        public string Prefix { get; set; }
        public string SerialNoFrom { get; set; }
        public string SerialNoTo { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string BoxNumber { get; set; }
        public Nullable<bool> Valid { get; set; }
        public string BinCenter { get; set; }
        public string ItemCode { get; set; }
        public string Type { get; set; }
        public string Colour { get; set; }
        public string Model { get; set; }
        public string UOM { get; set; }
        public string BizUnit { get; set; }
        public string QtyRaw { get; set; }
        public bool EmptyBinCenter { get; set; }
        public bool EmptyType { get; set; }
        public bool EmptyBizUnit { get; set; }
        public bool EmptyModel { get; set; }
        public bool EmptyColour { get; set; }
        public bool EmptyQty { get; set; }
        public bool ExistsSerial { get; set; }
        public bool ExistsIMEI { get; set; }
        public bool ExistsPIN { get; set; }
        public Nullable<bool> ExistsPrefixSerialFromTo { get; set; }
        public bool InvalidIMEI { get; set; }
        public bool HasSpecialCharIMEI { get; set; }
        public bool HasSpecialCharSerial { get; set; }
        public bool HasSpecialCharPIN { get; set; }
        public bool IsDuplicateIMEI { get; set; }
        public bool IsDuplicateSerial { get; set; }
        public bool IsDuplicatePIN { get; set; }
        public bool IsDuplicatePrefixSerialNo { get; set; }
        public bool IsRange { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public string ErrorMessage { get; set; }
    }
}
