//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnAllocation
    {
        public int ID { get; set; }
        public Nullable<int> OrderID { get; set; }
        public Nullable<int> ParentTransferID { get; set; }
        public int BizUnitID { get; set; }
        public int StatusID { get; set; }
        public string Reason { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AllocationDT { get; set; }
        public Nullable<System.DateTime> ApproveDT { get; set; }
        public Nullable<System.DateTime> AcceptDT { get; set; }
        public Nullable<System.DateTime> RejectDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public string CourierNum { get; set; }
        public string Despatcher { get; set; }
        public string ExtRefNo { get; set; }
        public string ExtUserID { get; set; }
        public string ApprovalRemark { get; set; }
        public string CancelRemark { get; set; }
        public bool IsPicked { get; set; }
        public bool IsEdit { get; set; }
        public bool IsFullAccept { get; set; }
        public string ReturnReason { get; set; }
        public string RejectRemark { get; set; }
        public Nullable<int> TransferRequestID { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
