//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnCollectionDO
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public string DOType { get; set; }
        public string Remark { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> ReceivedDT { get; set; }
        public Nullable<System.DateTime> IssuedDT { get; set; }
        public Nullable<System.DateTime> CollectedDT { get; set; }
        public int PrintCount { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> AccessID { get; set; }
    }
}
