//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnDelivery
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public Nullable<int> FromCenterID { get; set; }
        public string UploadType { get; set; }
        public string StoreNo { get; set; }
        public string SupplierNo { get; set; }
        public string DONumber { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public Nullable<System.DateTime> AcceptDT { get; set; }
        public string Subject { get; set; }
        public string Remark { get; set; }
        public string RejectionRemark { get; set; }
        public string ReturnReason { get; set; }
        public Nullable<int> AcceptAckStatus { get; set; }
        public Nullable<System.DateTime> AcceptAckDT { get; set; }
        public string PONumber { get; set; }
        public string AWBNumber { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> ReceivedDT { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> AccessID { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
    }
}
