//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnItemStatusConversion
    {
        public int ID { get; set; }
        public string ConversionType { get; set; }
        public int FromStatusID { get; set; }
        public int StatusConversionReasonID { get; set; }
        public int ConversionAccessID { get; set; }
        public int ConversionCenterID { get; set; }
        public System.DateTime ProcessDT { get; set; }
        public Nullable<System.DateTime> ConfirmDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public string Remark { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public string ErrorFileName { get; set; }
    }
}
