//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnReplaceEB
    {
        public int ID { get; set; }
        public int SalesOrderID { get; set; }
        public int CenterID { get; set; }
        public string CaseRemarks { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<System.DateTime> CollectedDT { get; set; }
        public int LastAccessID { get; set; }
        public Nullable<System.DateTime> ReversalDT { get; set; }
        public bool IsReversal { get; set; }
        public int StatusID { get; set; }
        public bool EmailSent { get; set; }
        public string DeliveredRemarks { get; set; }
        public string StatusRemark { get; set; }
        public string SubmittedBy { get; set; }
        public string CanceledRemarks { get; set; }
        public Nullable<System.DateTime> DeliveredDT { get; set; }
    }
}
