//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnRepair
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public int SalesID { get; set; }
        public string RMAType { get; set; }
        public string MSISDN { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Town { get; set; }
        public Nullable<int> StateID { get; set; }
        public string PostCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string ContactNo { get; set; }
        public string Complaints { get; set; }
        public string Diagnosis { get; set; }
        public string Remark { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public bool InWarranty { get; set; }
        public string CDate { get; set; }
        public string CTime { get; set; }
        public string UDate { get; set; }
        public string UTime { get; set; }
        public string FDate { get; set; }
        public string FTime { get; set; }
        public string RDate { get; set; }
        public string RTime { get; set; }
        public string XDate { get; set; }
        public string XTime { get; set; }
        public Nullable<int> AccessID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public string Level2Result { get; set; }
        public string Level2Remark { get; set; }
        public Nullable<bool> BeyondRepair { get; set; }
        public Nullable<int> StockOutID { get; set; }
        public Nullable<int> StockInID { get; set; }
        public string Level2PDate { get; set; }
        public string Level2PTime { get; set; }
        public Nullable<int> LoanID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public string StaffName { get; set; }
        public string IMEI { get; set; }
        public string Company { get; set; }
        public string SubmittedBy { get; set; }
        public string SendInDate { get; set; }
        public string SendInTime { get; set; }
        public string CaseRefNo { get; set; }
        public string OBAccessID { get; set; }
        public Nullable<int> OBRespCode { get; set; }
        public string OBRespMessage { get; set; }
        public Nullable<bool> IsDeviceSwap { get; set; }
        public Nullable<bool> IsStockReturn { get; set; }
    }
}
