//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnSalesOrder
    {
        public int ID { get; set; }
        public string ExtOrderID { get; set; }
        public int CenterID { get; set; }
        public System.DateTime OrderDT { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public string Remarks { get; set; }
        public string CancelRemarks { get; set; }
        public Nullable<int> CustCenterID { get; set; }
        public string C_Name { get; set; }
        public string C_ICNo { get; set; }
        public string C_ContactNo { get; set; }
        public string C_Address1 { get; set; }
        public string C_Address2 { get; set; }
        public string C_Address3 { get; set; }
        public string C_City { get; set; }
        public string C_State { get; set; }
        public string C_Postcode { get; set; }
        public string C_Country { get; set; }
        public string AP_Name { get; set; }
        public string AP_ICNo { get; set; }
        public string AP_OfficeNo { get; set; }
        public string AP_MobileNo { get; set; }
        public string CP_Name { get; set; }
        public string CP_ICNo { get; set; }
        public string CP_OfficeNo { get; set; }
        public string CP_MobileNo { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public int StatusID { get; set; }
        public int LastAccessID { get; set; }
        public string P_Address1 { get; set; }
        public string P_Address2 { get; set; }
        public string P_Address3 { get; set; }
        public string P_City { get; set; }
        public string P_State { get; set; }
        public string P_Postcode { get; set; }
        public string P_Country { get; set; }
    }
}
