//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnSession
    {
        public int ID { get; set; }
        public int ExtAppID { get; set; }
        public System.DateTime StartDT { get; set; }
        public Nullable<System.DateTime> ExpireDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public Nullable<System.DateTime> TriggerDT { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
