//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnSalesDelivery
    {
        public int ID { get; set; }
        public int SalesOrderID { get; set; }
        public string PrintDORemarks { get; set; }
        public string InTransitRemarks { get; set; }
        public string DeliveryRemarks { get; set; }
        public Nullable<int> AttemptNo { get; set; }
        public Nullable<System.DateTime> ConfirmPickingDT { get; set; }
        public Nullable<System.DateTime> ConfirmInTransitDT { get; set; }
        public Nullable<System.DateTime> DeliveryDT { get; set; }
        public string CNNo { get; set; }
        public string TrackingURL { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int LastAccessID { get; set; }
        public byte[] ShippingLabel { get; set; }
        public bool Active { get; set; }
        public int DeliveryTypeID { get; set; }
        public int StatusID { get; set; }
    }
}
