//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnSale
    {
        public int ID { get; set; }
        public string SalesRefID { get; set; }
        public int BizUnitID { get; set; }
        public int CenterID { get; set; }
        public Nullable<int> SalesTypeID { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateDT { get; set; }
        public System.DateTime SalesDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public Nullable<int> LastAccessID { get; set; }
    }
}
