//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnTransferRequest
    {
        public int ID { get; set; }
        public string ExtRefID { get; set; }
        public int FromCenterID { get; set; }
        public int ToCenterID { get; set; }
        public Nullable<int> TransferID { get; set; }
        public string Remark { get; set; }
        public string ApprovalRemark { get; set; }
        public string RejectRemark { get; set; }
        public string CancelRemark { get; set; }
        public string Reason { get; set; }
        public int TransferTypeID { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> RequestDT { get; set; }
        public Nullable<System.DateTime> ConfirmDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public Nullable<System.DateTime> ApproveDT { get; set; }
        public Nullable<System.DateTime> RejectDT { get; set; }
        public Nullable<System.DateTime> TransferDT { get; set; }
        public int StatusID { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
    }
}
