//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DynamicReportColumn.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class trnTransferDiagnosi
    {
        public int ID { get; set; }
        public int CenterID { get; set; }
        public string Remarks { get; set; }
        public string FileName { get; set; }
        public System.DateTime CreateDT { get; set; }
        public Nullable<System.DateTime> DiagnosisDT { get; set; }
        public Nullable<System.DateTime> CancelDT { get; set; }
        public Nullable<System.DateTime> LastUpdateDT { get; set; }
        public int AccessID { get; set; }
        public string OBRespMessage { get; set; }
        public string MDTSRespMessage { get; set; }
    }
}
